# Generated by Django 6.0.4 on 2026-05-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=100)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('RUPAY', 'RuPay'), ('AMEX', 'American Express')], max_length=15)),
                ('card_category', models.CharField(choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], max_length=10)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('gateway_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
