# Generated by Django 6.0.4 on 2026-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='wrong_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
